spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: okruti-ai
          location: global
          transport: rest
          credentials-uri: classpath:okruti-ai-token.json
          chat:
            options:
              model: gemini-2.0-flash-lite

  mail:
    host: smtp.hostinger.com
    port: 587
    username: support@peoplenest.in
    password: PeopleNest@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true